name: Source Workflow

on:
  push:

jobs:
  call-base-reusable:
    name: Call Base Reusable Workflow
    uses: ./.github/workflows/reusable.yml
    with:
      test-var: "Hello from root"
  call-subdir-reusable:
    name:  Call Reusable Workflow in Sub Directory
    uses: ./.github/workflows/subdir-reusable.yml
    with:
      test-var: "Hello from Sub Directory"